import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ConnectionConfig } from "../src/extension/connectionManager";
import type {
  TypeCategory,
  ValueSemantics,
} from "../src/extension/dbDrivers/types";

export type DbKind = "pg" | "mysql" | "mssql" | "oracle" | "sqlite";

export type ComparisonMode = "exact" | "prefix" | "presence";

export interface ColumnSpec {
  name: string;
  typeSql: string;
  seedValue: unknown;
  updateValue: unknown;
  filterValue: string;
  comparison?: ComparisonMode;
  filterable?: boolean;
  updatable?: boolean;
  readbackOnly?: boolean;
}

export interface MetadataExpectation {
  column: string;
  category: TypeCategory;
  filterable?: boolean;
  editable?: boolean;
  isAutoIncrement?: boolean;
  valueSemantics?: ValueSemantics;
}

export interface ReadbackExpectation {
  column: string;
  expected: unknown;
  comparison: ComparisonMode;
}

export interface DbFixture {
  kind: DbKind;
  displayName: string;
  connection: Omit<ConnectionConfig, "id">;
  bootstrapConnection?: Omit<ConnectionConfig, "id">;
  bootstrapSql?: string[];
  database: string;
  schema: string;
  table: string;
  view: string;
  functionName: string;
  procedureName: string;
  procedureColumn: string;
  procedureValue: unknown;
  columns: ColumnSpec[];
  metadataChecks: MetadataExpectation[];
  readbackChecks: ReadbackExpectation[];
  seedValues: Record<string, unknown>;
  updateValues: Record<string, unknown>;
  nullFilterColumn: string;
  emptyStringColumn: string;
  emptyStringLabelColumn: string;
  emptyStringLabelValue: string;
  emptyStringReadback: unknown;
  filterCases: Array<{
    column: string;
    value: string;
    comparison: ComparisonMode;
  }>;
  createTableSql: string;
  createViewSql: string;
  createFunctionSql: string;
  createProcedureSql: string;
  functionCallSql: string;
  functionExpected: string;
  procedureCallSql: string;
  teardownSql: string[];
  supportsFunctions?: boolean;
  supportsProcedures?: boolean;
  nullFilterRowValues?: Record<string, unknown>;
}

function suffixName(base: string, runId: string, upper = false): string {
  const name = `${base}_${runId}`;
  return upper ? name.toUpperCase() : name.toLowerCase();
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function quoteId(kind: DbKind, name: string): string {
  switch (kind) {
    case "mysql":
      return `\`${name.replace(/`/g, "``")}\``;
    case "mssql":
      return "[" + name.replace(/]/g, "]]") + "]";
    case "oracle":
      return name.toUpperCase();
    case "sqlite":
      return `"${name.replace(/"/g, '""')}"`;
    default:
      return `"${name.replace(/"/g, '""')}"`;
  }
}

function dbTableName(kind: DbKind, schema: string, table: string): string {
  const t = quoteId(kind, table);
  switch (kind) {
    case "pg":
      return `${quoteId(kind, schema)}.${t}`;
    case "mssql":
      return `${quoteId(kind, schema)}.${t}`;
    case "oracle":
      return t;
    case "mysql":
      return t;
    case "sqlite":
      return t;
  }
}

function dbObjectName(kind: DbKind, schema: string, name: string): string {
  return dbTableName(kind, schema, name);
}

function buildTableSql(
  kind: DbKind,
  schema: string,
  table: string,
  columns: ColumnSpec[],
): string {
  const idColumn =
    kind === "pg"
      ? `  ${quoteId(kind, "id")} BIGSERIAL PRIMARY KEY`
      : kind === "mysql"
        ? `  ${quoteId(kind, "id")} BIGINT AUTO_INCREMENT PRIMARY KEY`
        : kind === "mssql"
          ? `  ${quoteId(kind, "id")} INT IDENTITY(1,1) PRIMARY KEY`
          : kind === "sqlite"
            ? `  ${quoteId(kind, "id")} INTEGER PRIMARY KEY AUTOINCREMENT`
            : `  ${quoteId(kind, "id")} NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;

  const lines = [idColumn];
  for (const column of columns) {
    lines.push(`  ${quoteId(kind, column.name)} ${column.typeSql}`);
  }
  return `CREATE TABLE ${dbTableName(kind, schema, table)} (
${lines.join(",\n")}
);`;
}

function buildSeedValues(columns: ColumnSpec[]): Record<string, unknown> {
  return Object.fromEntries(
    columns
      .filter((column) => column.updatable !== false)
      .map((column) => [column.name, column.seedValue]),
  );
}

function buildUpdateValues(columns: ColumnSpec[]): Record<string, unknown> {
  return Object.fromEntries(
    columns
      .filter((column) => column.updatable !== false)
      .map((column) => [column.name, column.updateValue]),
  );
}

function buildFilterCases(columns: ColumnSpec[]): Array<{
  column: string;
  value: string;
  comparison: ComparisonMode;
}> {
  return columns
    .filter((column) => column.filterable !== false)
    .map((column) => ({
      column: column.name,
      value: column.filterValue,
      comparison: column.comparison ?? "exact",
    }));
}

function buildReadbackChecks(columns: ColumnSpec[]): ReadbackExpectation[] {
  return columns
    .filter((column) => column.readbackOnly)
    .map((column) => ({
      column: column.name,
      expected: column.seedValue,
      comparison: column.comparison ?? "exact",
    }));
}

function oracleDropBlock(objectType: string, objectName: string): string {
  return `BEGIN
  EXECUTE IMMEDIATE 'DROP ${objectType} ${objectName}';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-4043, -4080, -942) THEN
      RAISE;
    END IF;
END;
/`;
}

function buildPgFixture(runId: string): DbFixture {
  const schema = "public";
  const table = suffixName("rb_smk_pg", runId);
  const view = suffixName("rb_smk_pg_view", runId);
  const functionName = suffixName("rb_smk_pg_fn", runId);
  const procedureName = suffixName("rb_smk_pg_pr", runId);

  const columns: ColumnSpec[] = [
    {
      name: "small_int",
      typeSql: "smallint",
      seedValue: 7,
      updateValue: 8,
      filterValue: "7",
    },
    {
      name: "int_col",
      typeSql: "integer",
      seedValue: 42,
      updateValue: 43,
      filterValue: "42",
    },
    {
      name: "big_int",
      typeSql: "bigint",
      seedValue: "9007199254740991",
      updateValue: "9007199254740992",
      filterValue: "9007199254740991",
    },
    {
      name: "bool_col",
      typeSql: "boolean",
      seedValue: true,
      updateValue: false,
      filterValue: "true",
    },
    {
      name: "numeric_col",
      typeSql: "numeric(12,4)",
      seedValue: "12345.6789",
      updateValue: "54321.1234",
      filterValue: "12345.6789",
    },
    {
      name: "text_col",
      typeSql: "text",
      seedValue: "hello pg",
      updateValue: "hello pg updated",
      filterValue: "hello pg",
    },
    {
      name: "varchar_col",
      typeSql: "varchar(64)",
      seedValue: "alpha",
      updateValue: "beta",
      filterValue: "alpha",
    },
    {
      name: "bytea_col",
      typeSql: "bytea",
      seedValue: "\\xdeadbeef",
      updateValue: "\\xfeedface",
      filterValue: "deadbeef",
    },
    {
      name: "date_col",
      typeSql: "date",
      seedValue: "2026-04-15",
      updateValue: "2026-04-16",
      filterValue: "2026-04-15",
    },
    {
      name: "time_col",
      typeSql: "time",
      seedValue: "12:34:56",
      updateValue: "23:59:58",
      filterValue: "12:34:56",
    },
    {
      name: "ts_col",
      typeSql: "timestamp",
      seedValue: "2026-04-15 12:34:56",
      updateValue: "2026-04-16 01:02:03",
      filterValue: "2026-04-15 12:34:56",
    },
    {
      name: "tstz_col",
      typeSql: "timestamptz",
      seedValue: "2026-04-15T12:34:56Z",
      updateValue: "2026-04-16T01:02:03Z",
      filterValue: "2026-04-15 12:34:56",
      comparison: "prefix",
    },
    {
      name: "uuid_col",
      typeSql: "uuid",
      seedValue: "550e8400-e29b-41d4-a716-446655440000",
      updateValue: "550e8400-e29b-41d4-a716-446655440001",
      filterValue: "550e8400-e29b-41d4-a716-446655440000",
    },
    {
      name: "json_col",
      typeSql: "json",
      seedValue: '{"a":1}',
      updateValue: '{"a":2}',
      filterValue: "a",
    },
    {
      name: "jsonb_col",
      typeSql: "jsonb",
      seedValue: '{"b":2}',
      updateValue: '{"b":3}',
      filterValue: "b",
    },
    {
      name: "inet_col",
      typeSql: "inet",
      seedValue: "192.168.0.10",
      updateValue: "10.0.0.1",
      filterValue: "192.168.0.10",
    },
    {
      name: "cidr_col",
      typeSql: "cidr",
      seedValue: "192.168.0.0/24",
      updateValue: "10.0.0.0/8",
      filterValue: "192.168.0.0/24",
    },
    {
      name: "macaddr_col",
      typeSql: "macaddr",
      seedValue: "08:00:2b:01:02:03",
      updateValue: "08:00:2b:01:02:04",
      filterValue: "08:00:2b:01:02:03",
    },
    {
      name: "point_col",
      typeSql: "point DEFAULT '(1,2)'",
      seedValue: "(1,2)",
      updateValue: "(3,4)",
      filterValue: "1,2",
      comparison: "presence",
      filterable: false,
      updatable: false,
      readbackOnly: true,
    },
    {
      name: "circle_col",
      typeSql: "circle DEFAULT '<(1,2),3>'",
      seedValue: "<(1,2),3>",
      updateValue: "<(3,4),5>",
      filterValue: "1,2",
      comparison: "presence",
      filterable: false,
      updatable: false,
      readbackOnly: true,
    },
    {
      name: "bit_col",
      typeSql: "bit(1)",
      seedValue: "1",
      updateValue: "0",
      filterValue: "1",
    },
    {
      name: "varbit_col",
      typeSql: "varbit(8)",
      seedValue: "10101010",
      updateValue: "11110000",
      filterValue: "10101010",
    },
  ];

  return {
    kind: "pg",
    displayName: "PostgreSQL",
    connection: {
      name: `Smoke PostgreSQL ${runId}`,
      type: "pg",
      host: "localhost",
      port: 5432,
      database: "happy_pg_db",
      username: "db_admin",
      password: "pg_pass123",
    },
    database: "happy_pg_db",
    schema,
    table,
    view,
    functionName,
    procedureName,
    procedureColumn: "varchar_col",
    procedureValue: "proc row",
    columns,
    metadataChecks: [
      { column: "id", category: "integer", isAutoIncrement: true },
      { column: "numeric_col", category: "decimal" },
      { column: "bool_col", category: "boolean", valueSemantics: "boolean" },
      {
        column: "point_col",
        category: "spatial",
        filterable: false,
        editable: false,
      },
      {
        column: "circle_col",
        category: "spatial",
        filterable: false,
        editable: false,
      },
    ],
    readbackChecks: buildReadbackChecks(columns),
    seedValues: buildSeedValues(columns),
    updateValues: buildUpdateValues(columns),
    nullFilterColumn: "text_col",
    emptyStringColumn: "varchar_col",
    emptyStringLabelColumn: "text_col",
    emptyStringLabelValue: "pg empty insert",
    emptyStringReadback: "",
    filterCases: buildFilterCases(columns),
    createTableSql: buildTableSql("pg", schema, table, columns),
    createViewSql: `CREATE OR REPLACE VIEW ${dbObjectName("pg", schema, view)} AS
SELECT ${quoteId("pg", "id")}, ${quoteId("pg", "varchar_col")}, ${quoteId("pg", "text_col")}
FROM ${dbTableName("pg", schema, table)};`,
    createFunctionSql: `CREATE OR REPLACE FUNCTION ${dbObjectName("pg", schema, functionName)}(a integer, b integer)
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN a + b;
END;
$$;`,
    createProcedureSql: `CREATE OR REPLACE PROCEDURE ${dbObjectName("pg", schema, procedureName)}(p_text text)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO ${dbTableName("pg", schema, table)} (${quoteId("pg", "varchar_col")})
  VALUES (p_text);
END;
$$;`,
    functionCallSql: `SELECT ${dbObjectName("pg", schema, functionName)}(2, 3) AS value;`,
    functionExpected: "5",
    procedureCallSql: `CALL ${dbObjectName("pg", schema, procedureName)}(${sqlString("proc row")});`,
    teardownSql: [
      `DROP PROCEDURE IF EXISTS ${dbObjectName("pg", schema, procedureName)}(text);`,
      `DROP FUNCTION IF EXISTS ${dbObjectName("pg", schema, functionName)}(integer, integer);`,
      `DROP VIEW IF EXISTS ${dbObjectName("pg", schema, view)};`,
      `DROP TABLE IF EXISTS ${dbTableName("pg", schema, table)};`,
    ],
  };
}

function buildMySqlFixture(runId: string): DbFixture {
  const database = "happy_mysql_db";
  const schema = database;
  const table = suffixName("rb_smk_mysql", runId);
  const view = suffixName("rb_smk_mysql_view", runId);
  const functionName = suffixName("rb_smk_mysql_fn", runId);
  const procedureName = suffixName("rb_smk_mysql_pr", runId);

  const columns: ColumnSpec[] = [
    {
      name: "tiny_col",
      typeSql: "tinyint",
      seedValue: 1,
      updateValue: 2,
      filterValue: "1",
    },
    {
      name: "small_col",
      typeSql: "smallint",
      seedValue: 2,
      updateValue: 3,
      filterValue: "2",
    },
    {
      name: "medium_col",
      typeSql: "mediumint",
      seedValue: 300,
      updateValue: 301,
      filterValue: "300",
    },
    {
      name: "int_col",
      typeSql: "int",
      seedValue: 400,
      updateValue: 401,
      filterValue: "400",
    },
    {
      name: "big_col",
      typeSql: "bigint",
      seedValue: "9007199254740991",
      updateValue: "9007199254740992",
      filterValue: "9007199254740991",
    },
    {
      name: "dec_col",
      typeSql: "decimal(12,3)",
      seedValue: "12345.678",
      updateValue: "54321.123",
      filterValue: "12345.678",
    },
    {
      name: "float_col",
      typeSql: "float",
      seedValue: 1.25,
      updateValue: 2.5,
      filterValue: "1.25",
    },
    {
      name: "double_col",
      typeSql: "double",
      seedValue: 3.5,
      updateValue: 4.5,
      filterValue: "3.5",
    },
    {
      name: "bit_col",
      typeSql: "bit(1)",
      seedValue: 1,
      updateValue: 0,
      filterValue: "1",
    },
    {
      name: "bool_col",
      typeSql: "boolean",
      seedValue: true,
      updateValue: false,
      filterValue: "true",
    },
    {
      name: "char_col",
      typeSql: "char(10)",
      seedValue: "abc",
      updateValue: "xyz",
      filterValue: "abc",
    },
    {
      name: "varchar_col",
      typeSql: "varchar(64)",
      seedValue: "alpha",
      updateValue: "beta",
      filterValue: "alpha",
    },
    {
      name: "text_col",
      typeSql: "text",
      seedValue: "text body",
      updateValue: "text body upd",
      filterValue: "text body",
    },
    {
      name: "mediumtext_col",
      typeSql: "mediumtext",
      seedValue: "medium body",
      updateValue: "medium body upd",
      filterValue: "medium body",
    },
    {
      name: "longtext_col",
      typeSql: "longtext",
      seedValue: "long body",
      updateValue: "long body upd",
      filterValue: "long body",
    },
    {
      name: "binary_col",
      typeSql: "binary(4)",
      seedValue: "\\xdeadbeef",
      updateValue: "\\xfeedface",
      filterValue: "deadbeef",
      filterable: false,
    },
    {
      name: "varbinary_col",
      typeSql: "varbinary(16)",
      seedValue: "\\x0102030405060708",
      updateValue: "\\x0908070605040302",
      filterValue: "01020304",
      filterable: false,
    },
    {
      name: "blob_col",
      typeSql: "blob",
      seedValue: "\\x11223344",
      updateValue: "\\x55667788",
      filterValue: "11223344",
      filterable: false,
    },
    {
      name: "mediumblob_col",
      typeSql: "mediumblob",
      seedValue: "\\xaabbccdd",
      updateValue: "\\x01020304",
      filterValue: "aabbccdd",
      filterable: false,
    },
    {
      name: "longblob_col",
      typeSql: "longblob",
      seedValue: "\\x12345678",
      updateValue: "\\x87654321",
      filterValue: "12345678",
      filterable: false,
    },
    {
      name: "date_col",
      typeSql: "date",
      seedValue: "2026-04-15",
      updateValue: "2026-04-16",
      filterValue: "2026-04-15",
    },
    {
      name: "datetime_col",
      typeSql: "datetime",
      seedValue: "2026-04-15 12:34:56",
      updateValue: "2026-04-16 01:02:03",
      filterValue: "2026-04-15 12:34:56",
    },
    {
      name: "ts_col",
      typeSql: "timestamp",
      seedValue: "2026-04-15 12:34:56",
      updateValue: "2026-04-16 01:02:03",
      filterValue: "2026-04-15 12:34:56",
    },
    {
      name: "time_col",
      typeSql: "time",
      seedValue: "12:34:56",
      updateValue: "23:59:58",
      filterValue: "12:34:56",
    },
    {
      name: "year_col",
      typeSql: "year",
      seedValue: 2026,
      updateValue: 2027,
      filterValue: "2026",
    },
    {
      name: "json_col",
      typeSql: "json",
      seedValue: '{"a":1}',
      updateValue: '{"a":2}',
      filterValue: "a",
    },
    {
      name: "enum_col",
      typeSql: "enum('a','b','c')",
      seedValue: "b",
      updateValue: "c",
      filterValue: "b",
    },
    {
      name: "set_col",
      typeSql: "set('x','y','z')",
      seedValue: "x,y",
      updateValue: "y,z",
      filterValue: "x,y",
    },
    {
      name: "point_col",
      typeSql: "point DEFAULT (Point(1,2))",
      seedValue: "POINT(1 2)",
      updateValue: "POINT(3 4)",
      filterValue: "POINT(1 2)",
      comparison: "presence",
      filterable: false,
      updatable: false,
      readbackOnly: true,
    },
  ];

  return {
    kind: "mysql",
    displayName: "MySQL",
    connection: {
      name: `Smoke MySQL ${runId}`,
      type: "mysql",
      host: "localhost",
      port: 3306,
      database,
      username: "mysql_user",
      password: "mysql_pass123",
    },
    bootstrapConnection: {
      name: `Smoke MySQL bootstrap ${runId}`,
      type: "mysql",
      host: "localhost",
      port: 3306,
      database: "mysql",
      username: "root",
      password: "root_pass123",
    },
    bootstrapSql: ["SET GLOBAL log_bin_trust_function_creators = 1;"],
    database,
    schema,
    table,
    view,
    functionName,
    procedureName,
    procedureColumn: "varchar_col",
    procedureValue: "proc row",
    columns,
    metadataChecks: [
      { column: "id", category: "integer", isAutoIncrement: true },
      { column: "dec_col", category: "decimal" },
      { column: "bit_col", category: "integer", valueSemantics: "bit" },
      { column: "double_col", category: "float", filterable: true },
      {
        column: "point_col",
        category: "spatial",
        filterable: false,
        editable: false,
      },
    ],
    readbackChecks: buildReadbackChecks(columns),
    seedValues: buildSeedValues(columns),
    updateValues: buildUpdateValues(columns),
    nullFilterColumn: "text_col",
    emptyStringColumn: "varchar_col",
    emptyStringLabelColumn: "text_col",
    emptyStringLabelValue: "mysql empty insert",
    emptyStringReadback: "",
    filterCases: buildFilterCases(columns),
    createTableSql: buildTableSql("mysql", schema, table, columns),
    createViewSql: `CREATE OR REPLACE VIEW ${dbObjectName("mysql", schema, view)} AS
SELECT ${quoteId("mysql", "id")}, ${quoteId("mysql", "varchar_col")}, ${quoteId("mysql", "text_col")}
FROM ${dbTableName("mysql", schema, table)};`,
    createFunctionSql: `DELIMITER $$
CREATE FUNCTION ${dbObjectName("mysql", schema, functionName)}(a INT, b INT)
RETURNS INT
DETERMINISTIC
BEGIN
  RETURN a + b;
END $$
CREATE PROCEDURE ${dbObjectName("mysql", schema, procedureName)}(IN p_text VARCHAR(64))
BEGIN
  INSERT INTO ${dbTableName("mysql", schema, table)} (${quoteId("mysql", "varchar_col")})
  VALUES (p_text);
END $$
DELIMITER ;`,
    createProcedureSql: "",
    functionCallSql: `SELECT ${functionName}(2, 3) AS value;`,
    functionExpected: "5",
    procedureCallSql: `CALL ${procedureName}(${sqlString("proc row")});`,
    teardownSql: [
      `DROP PROCEDURE IF EXISTS ${dbObjectName("mysql", schema, procedureName)};`,
      `DROP FUNCTION IF EXISTS ${dbObjectName("mysql", schema, functionName)};`,
      `DROP VIEW IF EXISTS ${dbObjectName("mysql", schema, view)};`,
      `DROP TABLE IF EXISTS ${dbTableName("mysql", schema, table)};`,
    ],
  };
}

function buildMssqlFixture(runId: string): DbFixture {
  const database = "happy_mssql_db";
  const schema = "dbo";
  const table = suffixName("rb_smk_mssql", runId);
  const view = suffixName("rb_smk_mssql_view", runId);
  const functionName = suffixName("rb_smk_mssql_fn", runId);
  const procedureName = suffixName("rb_smk_mssql_pr", runId);

  const columns: ColumnSpec[] = [
    {
      name: "tiny_col",
      typeSql: "tinyint",
      seedValue: 1,
      updateValue: 2,
      filterValue: "1",
    },
    {
      name: "small_col",
      typeSql: "smallint",
      seedValue: 2,
      updateValue: 3,
      filterValue: "2",
    },
    {
      name: "int_col",
      typeSql: "int",
      seedValue: 4,
      updateValue: 5,
      filterValue: "4",
    },
    {
      name: "big_col",
      typeSql: "bigint",
      seedValue: "9007199254740991",
      updateValue: "9007199254740992",
      filterValue: "9007199254740991",
    },
    {
      name: "dec_col",
      typeSql: "decimal(18,4)",
      seedValue: "12345.6789",
      updateValue: "54321.1234",
      filterValue: "12345.6789",
    },
    {
      name: "num_col",
      typeSql: "numeric(18,4)",
      seedValue: "11111.2222",
      updateValue: "33333.4444",
      filterValue: "11111.2222",
    },
    {
      name: "float_col",
      typeSql: "float(53)",
      seedValue: 1.25,
      updateValue: 2.5,
      filterValue: "1.25",
    },
    {
      name: "real_col",
      typeSql: "real",
      seedValue: 3.5,
      updateValue: 4.5,
      filterValue: "3.5",
    },
    {
      name: "money_col",
      typeSql: "money",
      seedValue: 10.5,
      updateValue: 11.5,
      filterValue: "10.5",
    },
    {
      name: "smoney_col",
      typeSql: "smallmoney",
      seedValue: 1.25,
      updateValue: 2.5,
      filterValue: "1.25",
    },
    {
      name: "bit_col",
      typeSql: "bit",
      seedValue: 1,
      updateValue: 0,
      filterValue: "1",
    },
    {
      name: "char_col",
      typeSql: "char(10)",
      seedValue: "abc       ",
      updateValue: "xyz       ",
      filterValue: "abc",
    },
    {
      name: "varchar_col",
      typeSql: "varchar(64)",
      seedValue: "alpha",
      updateValue: "beta",
      filterValue: "alpha",
    },
    {
      name: "nchar_col",
      typeSql: "nchar(10)",
      seedValue: "абв       ",
      updateValue: "где       ",
      filterValue: "абв",
    },
    {
      name: "nvarchar_col",
      typeSql: "nvarchar(64)",
      seedValue: "привет",
      updateValue: "мир",
      filterValue: "привет",
    },
    {
      name: "text_col",
      typeSql: "text",
      seedValue: "text body",
      updateValue: "text body upd",
      filterValue: "text body",
      filterable: false,
      updatable: false,
    },
    {
      name: "ntext_col",
      typeSql: "ntext",
      seedValue: "ntext body",
      updateValue: "ntext body upd",
      filterValue: "ntext body",
      filterable: false,
      updatable: false,
    },
    {
      name: "binary_col",
      typeSql: "binary(4)",
      seedValue: "\\xdeadbeef",
      updateValue: "\\xfeedface",
      filterValue: "deadbeef",
    },
    {
      name: "varbinary_col",
      typeSql: "varbinary(16)",
      seedValue: "\\x0102030405060708",
      updateValue: "\\x0908070605040302",
      filterValue: "01020304",
    },
    {
      name: "image_col",
      typeSql: "image",
      seedValue: Buffer.from("11223344", "hex"),
      updateValue: Buffer.from("55667788", "hex"),
      filterValue: "11223344",
      filterable: false,
      updatable: false,
    },
    {
      name: "date_col",
      typeSql: "date",
      seedValue: "2026-04-15",
      updateValue: "2026-04-16",
      filterValue: "2026-04-15",
    },
    {
      name: "datetime2_col",
      typeSql: "datetime2(3)",
      seedValue: "2026-04-15 12:34:56.789",
      updateValue: "2026-04-16 01:02:03.456",
      filterValue: "2026-04-15 12:34:56.789",
    },
    {
      name: "datetimeoffset_col",
      typeSql: "datetimeoffset(7)",
      seedValue: "2026-04-15T12:34:56+00:00",
      updateValue: "2026-04-16T01:02:03+00:00",
      filterValue: "2026-04-15 12:34:56.000",
      comparison: "prefix",
      filterable: false,
    },
    {
      name: "smalldatetime_col",
      typeSql: "smalldatetime",
      seedValue: "2026-04-15 12:34:00",
      updateValue: "2026-04-16 01:02:00",
      filterValue: "2026-04-15 12:34:00",
    },
    {
      name: "time_col",
      typeSql: "time(7)",
      seedValue: "12:34:56.123",
      updateValue: "23:59:58.456",
      filterValue: "12:34:56.123",
    },
    {
      name: "unique_col",
      typeSql: "uniqueidentifier",
      seedValue: "550E8400-E29B-41D4-A716-446655440000",
      updateValue: "550E8400-E29B-41D4-A716-446655440001",
      filterValue: "550E8400-E29B-41D4-A716-446655440000",
    },
  ];

  return {
    kind: "mssql",
    displayName: "MSSQL",
    connection: {
      name: `Smoke MSSQL ${runId}`,
      type: "mssql",
      host: "localhost",
      port: 1433,
      database,
      username: "sa",
      password: "Happy_Pass123!",
      ssl: false,
      rejectUnauthorized: false,
    },
    bootstrapConnection: {
      name: `Smoke MSSQL bootstrap ${runId}`,
      type: "mssql",
      host: "localhost",
      port: 1433,
      database: "master",
      username: "sa",
      password: "Happy_Pass123!",
      ssl: false,
      rejectUnauthorized: false,
    },
    bootstrapSql: [
      `IF DB_ID(N'${database}') IS NULL CREATE DATABASE [${database}];`,
    ],
    database,
    schema,
    table,
    view,
    functionName,
    procedureName,
    procedureColumn: "varchar_col",
    procedureValue: "proc row",
    columns,
    metadataChecks: [
      { column: "id", category: "integer", isAutoIncrement: true },
      { column: "dec_col", category: "decimal" },
      { column: "bit_col", category: "integer", valueSemantics: "bit" },
      { column: "smalldatetime_col", category: "datetime", filterable: true },
      {
        column: "text_col",
        category: "text",
        filterable: false,
        editable: false,
      },
      {
        column: "ntext_col",
        category: "text",
        filterable: false,
        editable: false,
      },
      {
        column: "image_col",
        category: "binary",
        filterable: false,
        editable: false,
      },
    ],
    readbackChecks: buildReadbackChecks(columns),
    seedValues: buildSeedValues(columns),
    updateValues: buildUpdateValues(columns),
    nullFilterColumn: "nvarchar_col",
    emptyStringColumn: "varchar_col",
    emptyStringLabelColumn: "nvarchar_col",
    emptyStringLabelValue: "mssql empty insert",
    emptyStringReadback: "",
    filterCases: buildFilterCases(columns),
    createTableSql: buildTableSql("mssql", schema, table, columns),
    createViewSql: `CREATE OR ALTER VIEW ${dbObjectName("mssql", schema, view)}
AS
SELECT ${quoteId("mssql", "id")}, ${quoteId("mssql", "varchar_col")}, ${quoteId("mssql", "text_col")}
FROM ${dbTableName("mssql", schema, table)};`,
    createFunctionSql: `CREATE OR ALTER FUNCTION ${dbObjectName("mssql", schema, functionName)} (@a INT, @b INT)
RETURNS INT
AS
BEGIN
  RETURN @a + @b;
END;`,
    createProcedureSql: `CREATE OR ALTER PROCEDURE ${dbObjectName("mssql", schema, procedureName)} @p_text NVARCHAR(64)
AS
BEGIN
  INSERT INTO ${dbTableName("mssql", schema, table)} (${quoteId("mssql", "varchar_col")})
  VALUES (@p_text);
END;`,
    functionCallSql: `SELECT ${dbObjectName("mssql", schema, functionName)}(2, 3) AS value;`,
    functionExpected: "5",
    procedureCallSql: `EXEC ${dbObjectName("mssql", schema, procedureName)} @p_text = N'proc row';`,
    teardownSql: [
      `DROP PROCEDURE IF EXISTS ${dbObjectName("mssql", schema, procedureName)};`,
      `DROP FUNCTION IF EXISTS ${dbObjectName("mssql", schema, functionName)};`,
      `DROP VIEW IF EXISTS ${dbObjectName("mssql", schema, view)};`,
      `DROP TABLE IF EXISTS ${dbTableName("mssql", schema, table)};`,
    ],
  };
}

function buildOracleFixture(runId: string): DbFixture {
  const schema = "ORACLE_TEST_USER";
  const table = suffixName("rb_smk_ora", runId, true);
  const view = suffixName("rb_smk_ora_view", runId, true);
  const functionName = suffixName("rb_smk_ora_fn", runId, true);
  const procedureName = suffixName("rb_smk_ora_pr", runId, true);

  const columns: ColumnSpec[] = [
    {
      name: "N_COL",
      typeSql: "NUMBER",
      seedValue: 7,
      updateValue: 8,
      filterValue: "7",
    },
    {
      name: "N_PRC",
      typeSql: "NUMBER(10,2)",
      seedValue: "12345.67",
      updateValue: "54321.12",
      filterValue: "12345.67",
    },
    {
      name: "FLT_COL",
      typeSql: "FLOAT(126)",
      seedValue: 1.25,
      updateValue: 2.5,
      filterValue: "1.25",
    },
    {
      name: "BF_COL",
      typeSql: "BINARY_FLOAT",
      seedValue: 3.5,
      updateValue: 4.5,
      filterValue: "3.5",
    },
    {
      name: "BD_COL",
      typeSql: "BINARY_DOUBLE",
      seedValue: 5.5,
      updateValue: 6.5,
      filterValue: "5.5",
    },
    {
      name: "C_COL",
      typeSql: "CHAR(10)",
      seedValue: "abc       ",
      updateValue: "xyz       ",
      filterValue: "abc",
    },
    {
      name: "VC_COL",
      typeSql: "VARCHAR2(64)",
      seedValue: "alpha",
      updateValue: "beta",
      filterValue: "alpha",
    },
    {
      name: "NC_COL",
      typeSql: "NCHAR(10)",
      seedValue: "абв       ",
      updateValue: "где       ",
      filterValue: "абв",
    },
    {
      name: "NVC_COL",
      typeSql: "NVARCHAR2(64)",
      seedValue: "привет",
      updateValue: "мир",
      filterValue: "привет",
    },
    {
      name: "D_COL",
      typeSql: "DATE",
      seedValue: "2026-04-15 00:00:00",
      updateValue: "2026-04-16 00:00:00",
      filterValue: "2026-04-15",
    },
    {
      name: "TS_COL",
      typeSql: "TIMESTAMP",
      seedValue: "2026-04-15 12:34:56",
      updateValue: "2026-04-16 01:02:03",
      filterValue: "2026-04-15 12:34:56",
    },
    {
      name: "TSTZ_COL",
      typeSql: "TIMESTAMP WITH TIME ZONE",
      seedValue: new Date("2026-04-15T12:34:56Z"),
      updateValue: new Date("2026-04-16T01:02:03Z"),
      filterValue: "2026-04-15 12:34:56",
    },
    {
      name: "TSLTZ_COL",
      typeSql: "TIMESTAMP WITH LOCAL TIME ZONE",
      seedValue: new Date("2026-04-15T12:34:56Z"),
      updateValue: new Date("2026-04-16T01:02:03Z"),
      filterValue: "2026-04-15 12:34:56",
    },
    {
      name: "RAW_COL",
      typeSql: "RAW(16)",
      seedValue: Buffer.from("deadbeefcafebabe", "hex"),
      updateValue: Buffer.from("feedfacecafed00d", "hex"),
      filterValue: "deadbeefcafebabe",
      filterable: false,
    },
    {
      name: "CLOB_COL",
      typeSql: "CLOB",
      seedValue: undefined,
      updateValue: undefined,
      filterValue: "clob body",
      filterable: false,
      updatable: false,
    },
    {
      name: "NCLOB_COL",
      typeSql: "NCLOB",
      seedValue: undefined,
      updateValue: undefined,
      filterValue: "текст",
      filterable: false,
      updatable: false,
    },
    {
      name: "BLOB_COL",
      typeSql: "BLOB",
      seedValue: undefined,
      updateValue: undefined,
      filterValue: "11223344",
      filterable: false,
      updatable: false,
    },
    {
      name: "IDS_COL",
      typeSql:
        "INTERVAL DAY TO SECOND DEFAULT INTERVAL '1 02:03:04.5' DAY TO SECOND",
      seedValue: "1 02:03:04.5",
      updateValue: "2 03:04:05.6",
      filterValue: "02:03:04",
      filterable: false,
      updatable: false,
      readbackOnly: true,
    },
  ];

  return {
    kind: "oracle",
    displayName: "Oracle",
    connection: {
      name: `Smoke Oracle ${runId}`,
      type: "oracle",
      host: "localhost",
      port: 1521,
      database: "FREEPDB1",
      serviceName: "FREEPDB1",
      username: "oracle_test_user",
      password: "oracle_pass123",
    },
    database: "FREEPDB1",
    schema,
    table,
    view,
    functionName,
    procedureName,
    procedureColumn: "VC_COL",
    procedureValue: "proc row",
    columns,
    metadataChecks: [
      { column: "ID", category: "decimal", isAutoIncrement: true },
      { column: "N_COL", category: "decimal" },
      { column: "N_PRC", category: "decimal" },
      { column: "RAW_COL", category: "binary", filterable: false },
      { column: "D_COL", category: "datetime", filterable: true },
      { column: "TS_COL", category: "datetime", filterable: true },
      { column: "TSTZ_COL", category: "datetime", filterable: true },
      { column: "TSLTZ_COL", category: "datetime", filterable: true },
      {
        column: "IDS_COL",
        category: "interval",
        filterable: false,
        editable: false,
      },
    ],
    readbackChecks: buildReadbackChecks(columns),
    seedValues: buildSeedValues(columns),
    updateValues: buildUpdateValues(columns),
    nullFilterColumn: "NVC_COL",
    emptyStringColumn: "VC_COL",
    emptyStringLabelColumn: "NVC_COL",
    emptyStringLabelValue: "oracle empty insert",
    emptyStringReadback: null,
    filterCases: buildFilterCases(columns),
    createTableSql: buildTableSql("oracle", schema, table, columns),
    createViewSql: `CREATE OR REPLACE VIEW ${dbObjectName("oracle", schema, view)} AS
SELECT ${quoteId("oracle", "ID")}, ${quoteId("oracle", "VC_COL")}, ${quoteId("oracle", "D_COL")}
FROM ${dbTableName("oracle", schema, table)};`,
    createFunctionSql: `CREATE OR REPLACE FUNCTION ${dbObjectName("oracle", schema, functionName)}(a NUMBER, b NUMBER)
RETURN NUMBER
IS
BEGIN
  RETURN a + b;
END;
/`,
    createProcedureSql: `CREATE OR REPLACE PROCEDURE ${dbObjectName("oracle", schema, procedureName)}(p_text VARCHAR2)
IS
BEGIN
  INSERT INTO ${dbTableName("oracle", schema, table)} (${quoteId("oracle", "VC_COL")})
  VALUES (p_text);
END;
/`,
    functionCallSql: `SELECT ${dbObjectName("oracle", schema, functionName)}(2, 3) AS VALUE FROM dual;`,
    functionExpected: "5",
    procedureCallSql: `BEGIN
  ${dbObjectName("oracle", schema, procedureName)}(${sqlString("proc row")});
END;
/`,
    teardownSql: [
      oracleDropBlock(
        "PROCEDURE",
        dbObjectName("oracle", schema, procedureName),
      ),
      oracleDropBlock("FUNCTION", dbObjectName("oracle", schema, functionName)),
      oracleDropBlock("VIEW", dbObjectName("oracle", schema, view)),
      oracleDropBlock(
        "TABLE",
        `${dbObjectName("oracle", schema, table)} CASCADE CONSTRAINTS PURGE`,
      ),
    ],
  };
}

function buildSqliteFixture(runId: string): DbFixture {
  const database = "main";
  const schema = "main";
  const table = suffixName("rb_smk_sqlite", runId);
  const view = suffixName("rb_smk_sqlite_view", runId);
  const functionName = suffixName("rb_smk_sqlite_fn", runId);
  const procedureName = suffixName("rb_smk_sqlite_pr", runId);
  const filePath = join(tmpdir(), `rapidb-smoke-${runId}.sqlite`);

  const columns: ColumnSpec[] = [
    {
      name: "int_col",
      typeSql: "INTEGER",
      seedValue: 42,
      updateValue: 43,
      filterValue: "42",
    },
    {
      name: "bool_col",
      typeSql: "BOOLEAN",
      seedValue: true,
      updateValue: false,
      filterValue: "true",
    },
    {
      name: "dec_col",
      typeSql: "DECIMAL(12,4)",
      seedValue: "12345.6789",
      updateValue: "54321.1234",
      filterValue: "12345.6789",
    },
    {
      name: "text_col",
      typeSql: "TEXT",
      seedValue: "Hello SQLite",
      updateValue: "Hello SQLite Updated",
      filterValue: "Hello SQLite",
    },
    {
      name: "varchar_col",
      typeSql: "VARCHAR(64)",
      seedValue: "alpha",
      updateValue: "beta",
      filterValue: "alpha",
    },
    {
      name: "date_col",
      typeSql: "DATE",
      seedValue: "2026-04-15",
      updateValue: "2026-04-16",
      filterValue: "2026-04-15",
    },
    {
      name: "datetime_col",
      typeSql: "DATETIME",
      seedValue: "2026-04-15 10:30:00",
      updateValue: "2026-04-16 14:45:00",
      filterValue: "2026-04-15 10:30:00",
    },
    {
      name: "time_col",
      typeSql: "TIME",
      seedValue: "10:30:00",
      updateValue: "14:45:00",
      filterValue: "10:30:00",
    },
    {
      name: "uuid_col",
      typeSql: "UUID",
      seedValue: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      updateValue: "550e8400-e29b-41d4-a716-446655440000",
      filterValue: "aaaaaaaa",
    },
    {
      name: "json_col",
      typeSql: "JSON",
      seedValue: '{"name":"alpha"}',
      updateValue: '{"name":"beta"}',
      filterValue: "alpha",
    },
    {
      name: "note_lower",
      typeSql: "TEXT GENERATED ALWAYS AS (lower(text_col)) STORED",
      seedValue: "hello sqlite",
      updateValue: "hello sqlite updated",
      filterValue: "hello sqlite",
      updatable: false,
      readbackOnly: true,
    },
  ];

  return {
    kind: "sqlite",
    displayName: "SQLite",
    connection: {
      name: `Smoke SQLite ${runId}`,
      type: "sqlite",
      filePath,
    },
    database,
    schema,
    table,
    view,
    functionName,
    procedureName,
    procedureColumn: "varchar_col",
    procedureValue: "proc row",
    columns,
    metadataChecks: [
      { column: "id", category: "integer", isAutoIncrement: true },
      { column: "bool_col", category: "boolean", valueSemantics: "boolean" },
      { column: "date_col", category: "date", filterable: true },
      { column: "datetime_col", category: "datetime", filterable: true },
      { column: "time_col", category: "time", filterable: true },
      { column: "uuid_col", category: "uuid", filterable: true },
      { column: "json_col", category: "json", filterable: true },
      { column: "note_lower", category: "text", editable: false },
    ],
    readbackChecks: buildReadbackChecks(columns),
    seedValues: buildSeedValues(columns),
    updateValues: buildUpdateValues(columns),
    nullFilterColumn: "text_col",
    emptyStringColumn: "varchar_col",
    emptyStringLabelColumn: "text_col",
    emptyStringLabelValue: "sqlite empty insert",
    emptyStringReadback: "",
    filterCases: buildFilterCases(columns),
    createTableSql: buildTableSql("sqlite", schema, table, columns),
    createViewSql: `CREATE VIEW ${dbObjectName("sqlite", schema, view)} AS
SELECT ${quoteId("sqlite", "id")}, ${quoteId("sqlite", "varchar_col")}, ${quoteId("sqlite", "text_col")}
FROM ${dbTableName("sqlite", schema, table)};`,
    createFunctionSql: "-- SQLite does not support stored functions",
    createProcedureSql: "-- SQLite does not support stored procedures",
    functionCallSql: "",
    functionExpected: "",
    procedureCallSql: "",
    teardownSql: [
      `DROP VIEW IF EXISTS ${dbObjectName("sqlite", schema, view)};`,
      `DROP TABLE IF EXISTS ${dbObjectName("sqlite", schema, table)};`,
    ],
    supportsFunctions: false,
    supportsProcedures: false,
    nullFilterRowValues: {
      varchar_col: "proc row",
    },
  };
}

export function buildFixtures(runId: string): DbFixture[] {
  return [
    buildPgFixture(runId),
    buildMySqlFixture(runId),
    buildMssqlFixture(runId),
    buildOracleFixture(runId),
    buildSqliteFixture(runId),
  ];
}
