import "./harness";
import { fireEvent, screen, waitFor } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { TablePanel } from "../../src/extension/panels/tablePanel";
import type { ApplyResultPayload } from "../../src/shared/webviewContracts";
import { workflowState } from "./harness";
import { getScenario } from "./scenarios";
import { getBodyCell } from "./tableUi";

vi.doUnmock("../../src/webview/components/table/TableGrid");
vi.doMock("../../src/webview/components/MonacoEditor", () => ({
  MonacoEditor: ({
    initialValue,
    ariaLabel,
    readOnly,
    onChange,
  }: {
    initialValue?: string;
    ariaLabel?: string;
    readOnly?: boolean;
    onChange?: (value: string) => void;
  }) => (
    <textarea
      aria-label={ariaLabel}
      defaultValue={initialValue}
      readOnly={readOnly}
      onChange={(event) => onChange?.(event.target.value)}
    />
  ),
  connTypeToDialect: () => "postgresql",
}));

function edit(column: string, row: number, value: string) {
  fireEvent.doubleClick(getBodyCell(column, row));
  const inline = screen.queryByLabelText("Cell value");
  const input = inline ?? screen.getByLabelText("Cell data");
  fireEvent.change(input, { target: { value } });
  if (inline) fireEvent.keyDown(input, { key: "Enter" });
  else fireEvent.click(screen.getByRole("button", { name: "Apply" }));
}

const enabled =
  !process.env.RAPIDB_WORKFLOW_ENGINES ||
  process.env.RAPIDB_WORKFLOW_ENGINES.split(",")
    .map((id) => id.trim())
    .includes("postgres");

describe.runIf(enabled)(
  "postgres stage 4 real webview/host persisted edits",
  () => {
    it.each([
      "update",
      "insert",
    ] as const)("retains all pending edits and drafts when a bad %s blocks the mixed batch", async (bad) => {
      const { bootstrapWorkflowContext } = await import("./workflowContext");
      TablePanel.disposeAll();
      const scenario = getScenario("postgres");
      const config = scenario.buildConnection();
      const schema = `stage4_ui_${process.pid}_${Date.now().toString(36)}`;
      scenario.buildConnection = () => config;
      scenario.tableFixture.database = config.database ?? "";
      scenario.tableFixture.schema = schema;
      scenario.tableFixture.table = "edits";
      const context = await bootstrapWorkflowContext({
        scenario,
        state: workflowState as unknown as Parameters<
          typeof bootstrapWorkflowContext
        >[0]["state"],
      });
      let session:
        | import("./bridge/hostWebviewBridge").BridgeSession
        | undefined;
      try {
        await context.connect();
        const driver = context.connectionManager.getDriver(config.id);
        if (!driver) throw new Error("Missing driver");
        await driver.query(`CREATE SCHEMA "${schema}"`);
        await driver.query(
          `CREATE TABLE "${schema}".edits (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, amount numeric(4,2) DEFAULT 0, fraction numeric(2,2), u uuid)`,
        );
        await driver.query(
          `INSERT INTO "${schema}".edits(amount) VALUES(0),(0)`,
        );
        context.store.setSkipTableMutationPreview(false);
        session = (await context.openTableViewer()).session;
        await waitFor(() =>
          expect(getBodyCell("amount").textContent).toBe("0.00"),
        );
        edit("amount", 0, bad === "update" ? "1.239" : "2.34");
        await session.user.click(
          screen.getByRole("button", { name: "Add Row" }),
        );
        edit("amount", 0, bad === "insert" ? "1.239" : "3.45");
        const transaction = vi.spyOn(driver, "runTransaction");
        await session.user.click(
          screen.getByRole("button", { name: "Apply Changes" }),
        );
        await waitFor(() =>
          expect(
            session
              ?.hostMessages()
              .some((message) => message.type === "applyResult"),
          ).toBe(true),
        );
        const result = session
          .hostMessages()
          .filter((message) => message.type === "applyResult")
          .at(-1)?.payload as ApplyResultPayload;
        expect(result).toMatchObject({
          success: false,
          insertApplied: false,
          error: expect.stringContaining("2 fractional digits"),
        });
        expect(result.rowOutcomes?.[0]).toMatchObject({
          success: false,
          status: bad === "update" ? "prevalidation_failed" : "skipped",
        });
        expect(result.insertRowOutcomes?.[0]).toMatchObject({
          success: false,
          status: bad === "insert" ? "prevalidation_failed" : "skipped",
        });
        expect(transaction).not.toHaveBeenCalled();
        expect(
          session
            .hostMessages()
            .some((message) => message.type === "tableMutationPreview"),
        ).toBe(false);
        expect(
          screen
            .getByRole("button", { name: "Apply Changes" })
            .hasAttribute("disabled"),
        ).toBe(false);
        expect(getBodyCell("amount", 0).textContent).toBe(
          bad === "insert" ? "1.239" : "3.45",
        );
        expect(getBodyCell("amount", 1).textContent).toBe(
          bad === "update" ? "1.239" : "2.34",
        );
        expect(
          (
            await driver.query(
              `SELECT amount FROM "${schema}".edits ORDER BY id`,
            )
          ).rows.map((row) => row.__col_0),
        ).toEqual(["0.00", "0.00"]);

        // Correct the bad value and prove valid p=s and UUIDv7 survive preview/save/verification.
        edit("amount", bad === "insert" ? 0 : 1, "4.56");
        edit("fraction", 1, "0.12");
        edit("u", 1, "01890f47-6a42-7cc3-98c4-dc0c0c07398f");
        await session.user.click(
          screen.getByRole("button", { name: "Apply Changes" }),
        );
        await screen.findByRole("dialog");
        await session.user.click(
          screen.getByRole("button", { name: "Apply Changes" }),
        );
        await waitFor(() =>
          expect(
            session
              ?.hostMessages()
              .filter((message) => message.type === "applyResult").length,
          ).toBe(2),
        );
        const saved = session
          .hostMessages()
          .filter((message) => message.type === "applyResult")
          .at(-1)?.payload as ApplyResultPayload;
        expect(saved.success).toBe(true);
        expect(saved.warning).toBeUndefined();
        expect(transaction).toHaveBeenCalledOnce();
        expect(
          (
            await driver.query(
              `SELECT fraction,u FROM "${schema}".edits WHERE id=1`,
            )
          ).rows[0],
        ).toMatchObject({
          __col_0: "0.12",
          __col_1: "01890f47-6a42-7cc3-98c4-dc0c0c07398f",
        });
        await waitFor(() =>
          expect(screen.queryByText(/rows with unsaved changes/)).toBeNull(),
        );
        transaction.mockRestore();
      } finally {
        session?.unmount();
        TablePanel.disposeAll();
        const driver = context.connectionManager.getDriver(config.id);
        if (driver)
          await driver.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
        await context.dispose();
      }
    });
  },
);
