import type { EngineScenario } from "./types";

const oracle = (): EngineScenario => ({
  engineId: "oracle",
  connectionType: "oracle",
  displayName: "Oracle",
  buildConnection: (password: string = "oracle_pass123") => ({
    id: "workflow-oracle",
    name: "Workflow Oracle",
    type: "oracle",
    host: "127.0.0.1",
    port: 1521,
    database: "FREEPDB1",
    serviceName: "FREEPDB1",
    username: "oracle_test_user",
    password,
    folder: "Workflow Tests",
  }),
  capabilities: {
    primaryKey: true,
    rowUpdateByPk: true,
    structuredCell: true,
    multiRowPaste: true,
    csvExport: true,
    jsonExport: true,
    inlineInsert: true,
    deleteBySelection: true,
    supportsTransactions: true,
    driverEditorLanguage: "sql",
    driverSqlDialect: "plsql",
    defaultDatabase: "FREEPDB1",
  },
  preflight: ["SELECT 1 FROM dual"],
  createEntities: {
    description: "Create a small Oracle table and seed it.",
    runAs: "query",
    statements: [
      "BEGIN EXECUTE IMMEDIATE 'DROP TABLE workflow_todos'; EXCEPTION WHEN OTHERS THEN NULL; END;",
      `CREATE TABLE workflow_todos (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         title VARCHAR2(255) NOT NULL,
         done NUMBER(1) NOT NULL,
         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
       )`,
      `INSERT INTO workflow_todos (title, done) VALUES
         ('Write workflow test', 1)`,
      "INSERT INTO workflow_todos (title, done) VALUES ('Review PR', 0)",
      "INSERT INTO workflow_todos (title, done) VALUES ('Ship release', 0)",
    ],
    expectedNodeLabels: ["WORKFLOW_TODOS"],
  },
  tableFixture: {
    database: "FREEPDB1",
    schema: "ORACLE_TEST_USER",
    table: "WORKFLOW_TODOS",
    rowCount: 3,
    primaryKey: ["ID"],
    columns: [
      { name: "ID", type: "integer" },
      { name: "TITLE", type: "string" },
      { name: "DONE", type: "integer" },
    ],
    expectedAfterInsert: 4,
    expectedAfterUpdate: 4,
    expectedAfterDelete: 3,
  },
  export: {
    format: "csv",
    expectedRowCount: 3,
    expectedHeaderSubstrings: ["ID", "TITLE", "DONE", "CREATED_AT"],
    rowAssertions: [
      {
        description: "row 1 contains seeded title",
        contains: ["Write workflow test"],
      },
    ],
  },
  cleanup: {
    statements: [
      "BEGIN EXECUTE IMMEDIATE 'DROP TABLE workflow_todos'; EXCEPTION WHEN OTHERS THEN NULL; END;",
    ],
    verifyGone: [
      "SELECT 1 FROM user_tables WHERE table_name = 'WORKFLOW_TODOS'",
    ],
  },
});

export default oracle;
