export const RAPIDB_COMMANDS = {
  addConnection: "rapidb.addConnection",
  editConnection: "rapidb.editConnection",
  deleteConnection: "rapidb.deleteConnection",
  renameConnectionFolder: "rapidb.renameConnectionFolder",
  deleteConnectionFolder: "rapidb.deleteConnectionFolder",
  connect: "rapidb.connect",
  disconnect: "rapidb.disconnect",
  newQuery: "rapidb.newQuery",
  openTableData: "rapidb.openTableData",
  showDDL: "rapidb.showDDL",
  copyNodeName: "rapidb.copyNodeName",
  openRoutine: "rapidb.openRoutine",
  openHistoryEntry: "rapidb.openHistoryEntry",
  openBookmarkEntry: "rapidb.openBookmarkEntry",
  openErd: "rapidb.openErd",
  deleteBookmark: "rapidb.deleteBookmark",
  clearBookmarks: "rapidb.clearBookmarks",
  clearHistory: "rapidb.clearHistory",
  disconnectAll: "rapidb.disconnectAll",
  refresh: "rapidb.refresh",
  showConnectedOnly: "rapidb.showConnectedOnly",
  showAllConnections: "rapidb.showAllConnections",
} as const;
